package de.viper.survivalplus.commands;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

public class ClearChatCommand implements CommandExecutor {

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (!sender.hasPermission("survivalplus.clearchat")) {
            sender.sendMessage("§cDu hast keine Rechte, den Chat zu löschen.");
            return true;
        }

        // Chat für alle "leeren" (100 leere Zeilen senden)
        for (int i = 0; i < 100; i++) {
            Bukkit.broadcastMessage(" ");
        }

        Bukkit.broadcastMessage("§aDer Chat wurde von §e" + sender.getName() + " §agelöscht.");

        return true;
    }
}
