package de.viper.survivalplus.listeners;

import org.bukkit.ChatColor;
import org.bukkit.entity.ArmorStand;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractAtEntityEvent;

public class ArmorStandDestroyListener implements Listener {

    @EventHandler
    public void onArmorStandInteract(PlayerInteractAtEntityEvent event) {
        if (!(event.getRightClicked() instanceof ArmorStand armorStand)) return;

        Player player = event.getPlayer();

        if (!player.hasPermission("survivalplus.armorstand.destroy")) {
            player.sendMessage(ChatColor.RED + "Du hast keine Berechtigung, diesen ArmorStand zu entfernen.");
            return;
        }

        armorStand.remove();
        player.sendMessage(ChatColor.YELLOW + "ArmorStand wurde erfolgreich entfernt.");
        event.setCancelled(true);
    }
}
